const data = {
  product: [
    {
      id: '1',
      name: 'KSL 01',
      price: 2000,
      rating: 3.5,
      numReviews: 80,
      type: 'loafer',
      imgUrl: '/images/products/shoe1.jpg',
    },
    {
      id: '2',
      name: 'Royal S 01',
      price: 6000,
      rating: 4.5,
      numReviews: 1000,
      type: 'sneaker',
      imgUrl: '/images/products/shoe3.png',
    },
    {
      id: '3',
      name: 'KSW 01',
      price: 2500,
      rating: 2.5,
      numReviews: 100,
      type: 'loafer',
      imgUrl: '/images/products/shoe2.jpg',
    },

    {
      id: '4',
      name: 'KSL 01',
      price: 2000,
      rating: 3.5,
      numReviews: 80,
      type: 'loafer',
      imgUrl: '/images/products/shoe1.jpg',
    },
    {
      id: '5',
      name: 'Royal S 01',
      price: 6000,
      rating: 4.5,
      numReviews: 1000,
      type: 'sneaker',
      imgUrl: '/images/products/shoe3.png',
    },
    {
      id: '6',
      name: 'KSW 01',
      price: 2500,
      rating: 2.5,
      numReviews: 100,
      type: 'loafer',
      imgUrl: '/images/products/shoe2.jpg',
    },
  ],
};
export default data;
